# Generated by Django 5.0.6 on 2024-07-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0004_passenger_delete_passanger"),
    ]

    operations = [
        migrations.RenameField(
            model_name="passenger",
            old_name="fligts",
            new_name="flights",
        ),
    ]
