# Generated by Django 5.1.1 on 2024-10-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0006_remove_post_likes_post_liked_by_alter_post_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.CharField(max_length=280),
        ),
    ]
