# Generated by Django 5.1.1 on 2024-10-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0008_user_timezone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="timezone",
        ),
    ]
