# Generated by Django 5.0.6 on 2024-07-28 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_auctlisting_bids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctlisting",
            name="photo_url",
            field=models.URLField(validators=[django.core.validators.URLValidator]),
        ),
        migrations.AlterField(
            model_name="auctlisting",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.DecimalValidator(10, 2),
                    django.core.validators.MinValueValidator(0.0),
                ],
            ),
        ),
        migrations.DeleteModel(
            name="Bids",
        ),
    ]
