# Generated by Django 5.0.6 on 2024-08-07 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_auctlisting_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctlisting",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
