# Generated by Django 5.0.6 on 2024-08-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_alter_auctlisting_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctlisting",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
