# Generated by Django 5.0.6 on 2024-08-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_alter_bids_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctlisting",
            name="number_bids",
            field=models.IntegerField(default=0),
        ),
    ]
