# Generated by Django 5.0.6 on 2024-08-14 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_auctlisting_number_bids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctlisting",
            name="photo_url",
            field=models.URLField(
                blank=True,
                default="https://www.cagd.gov.gh/wp-content/themes/consultix/images/no-image-found-360x250.png",
                validators=[django.core.validators.URLValidator],
            ),
        ),
    ]
