# Generated by Django 5.0.6 on 2024-08-14 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_alter_auctlisting_photo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="watchlisted_by", to="auctions.auctlisting"
            ),
        ),
        migrations.AlterField(
            model_name="auctlisting",
            name="photo_url",
            field=models.URLField(
                blank=True, validators=[django.core.validators.URLValidator]
            ),
        ),
    ]
