export const frontMuscleGroupNames = {
  abdominals: 'abdominals',
  adductors: 'adductors',
  biceps: 'biceps',
  calves: 'calves',
  deltoidAnterior: 'deltoid-anterior',
  deltoidLateral: 'deltoid-lateral',
  forearms: 'forearms',
  neck: 'neck',
  obliques: 'obliques',
  pectoralisMiddleLower: 'pectoralis-middle-lower',
  pectoralisUpper: 'pectoralis-upper',
  quadriceps: 'quadriceps',
  trapsUpper: 'traps-upper',
};

export const backMuscleGroupNames = {
  adductors: 'adductors',
  calves: 'calves',
  deltoidLateral: 'deltoid-lateral',
  deltoidPosterior: 'deltoid-posterior',
  forearms: 'forearms',
  glutes: 'glutes',
  hamstrings: 'hamstrings',
  lats: 'lats',
  lowerback: 'lowerback',
  neck: 'neck',
  trapsMiddleLower: 'traps-middle-lower',
  trapsUpper: 'traps-upper',
  triceps: 'triceps',
};
