# Generated by Django 5.1.2 on 2024-12-18 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_musclegroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("video_link", models.URLField(blank=True, max_length=255, null=True)),
                ("gif_link", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "primary_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_exercises",
                        to="api.musclegroup",
                    ),
                ),
                (
                    "secondary_group",
                    models.ManyToManyField(
                        blank=True,
                        related_name="secondary_exercises",
                        to="api.musclegroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mistake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mistakes",
                        to="api.exercise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="api.exercise",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
