# Generated by Django 5.1.2 on 2024-12-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_exercise_mistake_step"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="gif_link",
            new_name="gif_link_front",
        ),
        migrations.AddField(
            model_name="exercise",
            name="gif_link_side",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
