# Generated by Django 5.1.2 on 2025-02-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_gif_link_exercise_gif_link_front_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
