# Generated by Django 5.1.6 on 2025-02-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_exercise_created_at_alter_exercise_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name="musclegroup",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
