# Generated by Django 5.1.6 on 2025-02-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_exercise_slug_alter_musclegroup_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
