# Generated by Django 5.1.6 on 2025-02-25 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_exercise_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="secondary_group",
            new_name="secondary_groups",
        ),
    ]
